export const BAVARIAN_REGIONS = [
  {
    region: "Oberbayern",
    districts: [
      "Ingolstadt",
      "München",
      "Rosenheim",
      "Altötting",
      "Bad Tölz-Wolfratshausen",
      "Berchtesgadener Land",
      "Dachau",
      "Ebersberg",
      "Eichstätt",
      "Erding",
      "Freising",
      "Fürstenfeldbruck",
      "Garmisch-Partenkirchen",
      "Landsberg am Lech",
      "Miesbach",
      "Mühldorf am Inn",
      "München (Landkreis)",
      "Neuburg-Schrobenhausen",
      "Pfaffenhofen an der Ilm",
      "Rosenheim (Landkreis)",
      "Starnberg",
      "Traunstein",
      "Weilheim-Schongau",
    ],
  },
  {
    region: "Niederbayern",
    districts: [
      "Landshut",
      "Passau",
      "Straubing",
      "Deggendorf",
      "Freyung-Grafenau",
      "Kelheim",
      "Landshut (Landkreis)",
      "Passau (Landkreis)",
      "Regen",
      "Rottal-Inn",
      "Straubing-Bogen",
      "Dingolfing-Landau",
    ],
  },
  {
    region: "Oberpfalz",
    districts: [
      "Amberg",
      "Regensburg",
      "Weiden i.d.OPf.",
      "Amberg-Sulzbach",
      "Cham",
      "Neumarkt i.d.OPf.",
      "Neustadt a.d.Waldnaab",
      "Regensburg (Landkreis)",
      "Schwandorf",
      "Tirschenreuth",
    ],
  },
  {
    region: "Oberfranken",
    districts: [
      "Bamberg",
      "Bayreuth",
      "Coburg",
      "Hof",
      "Bamberg (Landkreis)",
      "Bayreuth (Landkreis)",
      "Coburg (Landkreis)",
      "Forchheim",
      "Hof (Landkreis)",
      "Kronach",
      "Kulmbach",
      "Lichtenfels",
      "Wunsiedel i.Fichtelgebirge",
    ],
  },
  {
    region: "Mittelfranken",
    districts: [
      "Ansbach",
      "Erlangen",
      "Fürth",
      "Nürnberg",
      "Schwabach",
      "Ansbach (Landkreis)",
      "Erlangen-Höchstadt",
      "Fürth (Landkreis)",
      "Nürnberger Land",
      "Neustadt a.d.Aisch-Bad Windsheim",
      "Roth",
      "Weißenburg-Gunzenhausen",
    ],
  },
  {
    region: "Unterfranken",
    districts: [
      "Aschaffenburg",
      "Schweinfurt",
      "Würzburg",
      "Aschaffenburg (Landkreis)",
      "Bad Kissingen",
      "Rhön-Grabfeld",
      "Haßberge",
      "Kitzingen",
      "Miltenberg",
      "Main-Spessart",
      "Schweinfurt (Landkreis)",
      "Würzburg (Landkreis)",
    ],
  },
  {
    region: "Schwaben",
    districts: [
      "Augsburg",
      "Kaufbeuren",
      "Kempten (Allgäu)",
      "Memmingen",
      "Aichach-Friedberg",
      "Augsburg (Landkreis)",
      "Dillingen a.d.Donau",
      "Günzburg",
      "Neu-Ulm",
      "Lindau (Bodensee)",
      "Ostallgäu",
      "Unterallgäu",
      "Donau-Ries",
      "Oberallgäu",
    ],
  },
];

// Flache Liste aller erlaubten Landkreise und kreisfreien Städte.
// Diese Liste verwenden wir insbesondere für die serverseitige Validierung.
export const BAVARIAN_DISTRICTS = BAVARIAN_REGIONS.flatMap(
  (region) => region.districts
);